### ISSUE TITLE
--save not necessary anymore with npm -v 5+

### ISSUE THREAD

**Issue by MynahMarie** [foundersandcoders/npm-introduction#3]
https://github.com/foundersandcoders/npm-introduction/edit/master/README.md#L40
`npm install <package-name> --save` (this is the default for `npm install` in npm5)`

Instead of saying "this is the default...", maybe we should make it  bit clearer that the --save option is not necessary with newer versions of npm? I know that in FACN3 alot of people didn't understand that and kept doing the --save until the end of the cohort :laughing:

**Comment by oliverjam** [comment]
Yeah that could be clearer. How about
>`npm install <package-name> --save` (You can leave off the `--save` if you're using npm v5 or above as it's now the default)

**Comment by zurda** [comment]
Thanks for the comments! We'll fix this prior to the next one

**Comment by zurda** [comment]
@oliverjam @MynahMarie I've created a pull request which attempts to address this.
