### ISSUE TITLE
Introduce npm scripts

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/npm-introduction#6]
Should we introduce the concept of npm scripts at this point? @shiryz raised a good point on [this MR adding instructions for setting up nodemon](https://github.com/foundersandcoders/ws-pure-functions-easy-testing/pull/9)—students have no idea what an npm script is at that point.

I'm happy to add a little intro here, but I'm not sure if it would end up adding even more noise to what is already a ton of stuff to learn before they can start actually testing.

**Comment by zurda** [comment]
Good point @shiryz & @oliverjam .  

With FAC-16 we explained scripts during the code along (day 1 after lunch), but the Fizzbuzz workshop has a `package.json` file with a script in it already (scheduled before lunch). I feel silly for not noticing this last week...

As far as I can remember the class went through the intro to npm fairly quickly, so IMO adding an additional script example makes sense. Another benefit would be that it would make the difference between `node` and `npm` a bit clearer (it is confusing at first).

My suggestion would be to keep the script as simple as possible, for example a `start` script that runs `node index.js`.

**Comment by oliverjam** [comment]
I think until we introduce the concept of running local JS files with Node (in Week 4) it might be less confusing to restrict script usage to just running local dependencies (like Tape).

I'll maybe show that `"test": "tape index.test.js"` is a shortcut for directly running `./node_modules/bin/tape index.test.js` in your terminal.

Is that confusing or does it demystify scripts a bit?

**Comment by zurda** [comment]
I think it makes sense. It's just a bit odd that we're installing tape and adding it to a script before explaining what it is. But I can't think of an alternative and the students seemed OK with this intro.  

Also, (and I might be nit picky so please call me out if I'm overthinking this), the Fizzbuzz workshop has a script using `node` for running tests, so I think we should change it there as well. 

The current json file in fizzbuzz: 

```json
"scripts": {
    "test": "node test.js | tap-spec"
  },
```

**Comment by oliverjam** [comment]
Ah yes we probably should. I think you can run Tape directly or via Node (since you import the library directly in the JS test file)

**Comment by shiryz** [comment]
I think it's okay to introduce scripts this week as a shortcut, the "aha moment" will happen during week 4 but that's cool too.
